# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://cxh.me
title: CXH.ME
author: Harry Chen
simple_search: http://google.com/search
lang: zh-CN

description: 北航本，清华硕，现就职于支付宝北京（北厂环球车间OceanBase生产线）
keywords: 分布式,oceanbase,数据库,挨踢人生,世情百态

subtitle: 每当我找不到存在的意义，每当我迷失在黑夜里，夜空中最亮的星，请照亮我前行
sub_from: 《夜空中最亮的星》
subpic: star_in_the_sky.jpg


# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: sdqxcxh@gmail.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /:year/:month/:day/:title/
source: source
destination: www
plugins: plugins
code_dir: downloads/code
pandoc_dir: pandoc
category_dir: category
#pandoc:
  #format: html
  #extensions: [smart, mathjax]
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 30          # Posts per page on the blog index
pagination_dir:  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "阅读全文"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
sidebar: false
default_asides: [
    custom/asides/about.html,
    custom/asides/profile.html,
    custom/asides/notice.html,
    asides/recent_posts.html
    ]
# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
#blog_index_asides:
#post_asides:
#page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: chenxiaohui
github_repo_count: 5
github_show_profile_link: false
github_skip_forks: true

# Twitter
twitter_user: sdqxcxh
twitter: Harry Chen
twitter_show: false
twitter_tweet_button: false

# Google +1
google_plus_one: false
google_plus_one_size: medium
google_plus: Harry Chen
google_plus_user: sdqxcxh

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: harrychen
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: false
facebook: Harry Chen
facebook_user: sdqxcxh

#weibo
weibo_xiu: false
weibo: CXH.ME
weibo_user: sdqxcxh

#renren
renren: Harry Chen
renren_user: sdqxcxh

#jiathis
jiathis: false

#cnzz
cnzz: true
